config/routes.rb
Rails.application.routes.draw do

  resources :articles
  resources :questions
  resources :hospital_lists
  resources :doctor_lists, except: [:edit, :update, :show]
  resources :hospital_verification_requests, except: [:edit, :update]
  resources :doctor_verification_requests, except: [:edit, :update]

  get 'tags/:tag', to: 'questions#index', as: "tag"
  get 'questions/autocomplete_tag_name'
  get 'questions/autocomplete_question_body'
  get 'articles/autocomplete_article_title'

  resources :reviews
  resources :hospitals
  resources :answers, except: [:show]
  resources :profiles, only: [:show, :index] #todo do we really need show????
  resource  :dashboard, only: :show
  resources :doctors
  resources :hospital_likes, only: [:new, :create, :destroy]
  resources :answer_likes, only: [:new, :create, :destroy]
  resources :doctor_likes, only: [:new, :create, :destroy]
  resources :follows, only: [:new, :create, :destroy]
  resources :ratings, only: :update

  post 'answer' => 'questions#answer'
  get 'hospitals/:id/doctors' => 'hospitals#our_doctors', as: :our_doctors

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => :registrations }

  root 'homes#show'

  mount Ckeditor::Engine => '/ckeditor'
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user, -> { where(role: "user") } #belongs to owner? or a better name?
  has_many :answers, :dependent => :destroy
  has_many :follows
  has_many :users, through: :follows, class_name: 'User'
  has_many :taggings
  has_many :tags, through: :taggings

  validates_presence_of :body, :user
  validate :asked_by_a_client?

  accepts_nested_attributes_for :answers

  scope :contains_text, -> (text) { where("body like ?", "%#{text}%")}

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end

  def self.tagged_with(name)
    Tag.find_by_name(name.strip.split(',')).try(:questions)
  end

  def asked_by_a_client?
    errors.add(:user, "must be a client to ask questions") unless self.user and self.user.role == 'user'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  autocomplete :tag, :name
  autocomplete :question, :body
  before_action :set_question, only: [:show, :update, :destroy, :answer]
  before_action :set_answers, only: [:show, :answer]
  # load_and_authorize_resource

  # GET /questions
  # GET /questions.json
  def index
    authorize! :read, Question
    if current_user.interests
      @interest_questions = Question.tagged_with(current_user.interests) #todo how are interests compiled?
    end
    if params[:q]
      @questions = Question.contains_text("%#{params[:q]}%").order('created_at DESC')
    else
      @questions = Question.all.order('created_at DESC')
    end
    @my_questions = current_user.questions.order('created_at DESC')
    @my_follows = current_user.followed_questions.order('created_at DESC')
    @interests = "" #todo how are interests compiled?
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    authorize! :read, Question
    @answer = @question.answers.new
  end

  # GET /questions/new
  def new
    authorize! :create, Question
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
    authorize! :update, Question
    @question = current_user.questions.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    authorize! :create, Question
    @question = current_user.questions.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    authorize! :update, Question
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    authorize! :destroy, Question
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def answer
    authorize! :create, Answer
    @answer = @question.answers.build(answer_params)
    @answer.user = current_user
    respond_to do |format|
      if @answer.save
        format.html { redirect_to @question, notice: 'Answer was successfully posted.' }
      else
        format.html { render :show }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    def set_answers
      @answers = @question.answers.order('created_at desc')
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:caption, :body, :user_id, :doctor_id, :all_tags)
    end

    def answer_params
      params.require(:answer).permit(:question_id, :content, :doctor_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def tag_links(tags)
    tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ")
  end

  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end
end

app/views/questions/_all.html.haml
.row
  - @questions.each do |question|
    .col.s12.m6
      .card-panel.question-panel
        .row
          .col.s4
            = image_tag(question.user.image.url(:small), class: "responsive-img activator")
          .col.s8
            .question-body
              = question.body
            .right.profile= time_ago_in_words(question.created_at)
        .row
          = link_to 'View', question, class: 'mdi-image-remove-red-eye btn'
          -if verified_doctor?
            = link_to 'Answer', new_answer_path(question: question), class: 'waves-effect waves-light btn mdi-action-announcement'
          - unless question.users.include?(current_user)
            .right= link_to 'Follow', follows_path(:follow => {question_id: question.id}), method: :post, class: 'mdi-maps-directions-walk'

app/views/questions/_answer_form.html.haml
.row
  = form_tag action: 'answer', id: @question do
    - if @answer.errors.any?
      #error_explanation
        %h2
          = pluralize(@answer.errors.count, "error")
          prohibited this answer from being saved:
        %ul
          - @answer.errors.full_messages.each do |message|
            %li= message
    .row
      .input-field.col.s12
        = text_area 'answer', :content, class: "validate materialize-textarea"
        %label{:for => "answer_content"} Answer
    .modal-footer
      = submit_tag 'Post Help', class: "btn-flat modal-action"

app/views/questions/_followed.html.haml
.row
  - @my_follows.each do |question|
    .col.s12.m6
      .card-panel.question-panel
        .row
          .col.s4
            = image_tag(question.user.image.url(:small), class: "responsive-img activator")
          .col.s8
            .question-body
              = question.body
            .right.profile= time_ago_in_words(question.created_at)
        .row
          = link_to 'View', question, class: 'mdi-image-remove-red-eye btn'
          .btn.disabled
            .mdi-action-announcement= question.answers.count
            .mdi-maps-directions-walk= question.follows.count

app/views/questions/_form.html.haml
.form-wrapper
  .row.form-body
    = form_for(@question) do |f|
      - if @question.errors.any?
        #error_explanation
          %h2
            = pluralize(@question.errors.count, "error")
            prohibited this question from being saved:
          %ul
            - @question.errors.full_messages.each do |message|
              %li= message
      .row
        .input-field.col.s12
          = f.text_area :body, class: "validate materialize-textarea"
          %label{:for => "question_body"} Ask a brief question
      .row
        .input-field.col.s12
          = f.text_field :all_tags, class: "validate"
          %label{:for => "question_all_tags"} Tags separated with commas, e.g eyes, pregnancy...
      .actions
        = f.submit "Ask the Doc", class: "btn"

app/views/questions/_header.html.haml
.row
  .col.s12
    %ul.tabs
      %li.tab.col.s3.active
        = link_to "All", "#all"
      %li.tab.col.s3
        = link_to "Following", "#following"
      %li.tab.col.s3
        = link_to "Interests", "#interests"
      - if client?
        %li.tab.col.s3
          = link_to "Mine", "#mine"

app/views/questions/_interest.html.haml
-if current_user.interests
  .row
    - @interest_questions.try(:each) do |question|
      .col.s12.m6
        .card-panel.question-panel
          .row
            .col.s4
              = image_tag(question.user.image.url(:small), class: "responsive-img activator")
            .col.s8
              .question-body
                = question.body
              .right.profile= time_ago_in_words(question.created_at)
          .row
            = link_to 'View', question, class: 'mdi-image-remove-red-eye btn'
            - unless question.users.include?(current_user)
              .right= link_to 'Follow', follows_path(:follow => {question_id: question.id}), method: :post, class: 'mdi-maps-directions-walk'
            .btn.disabled
              .mdi-action-announcement= question.answers.count
              .mdi-maps-directions-walk= question.follows.count

app/views/questions/_mine.html.haml
.row
  - @my_questions.each do |question|
    .col.s12.m6
      .card-panel.question-panel
        .row
          .col.s4
            = image_tag(question.user.image.url(:small), class: "responsive-img activator")
          .col.s8
            .question-body
              = question.body
            .right.profile= time_ago_in_words(question.created_at)
        .row
          = link_to 'View', question, class: 'mdi-image-remove-red-eye btn'
          .btn.disabled
            .mdi-action-announcement= question.answers.count
            .mdi-maps-directions-walk= question.follows.count

app/views/questions/_search.html.haml
= form_tag [:questions], {:method => :get, :class => 'navbar-search pull-right', style:'margin-right:15px;'} do
  = text_field_tag 'q', @q, { placeholder: "Search Questions", autocomplete: questions_autocomplete_question_body_path }

app/views/questions/edit.html.haml
%h5.center-align Editing Question
= render 'form'

app/views/questions/followed.html.haml
%section.views
  = render partial: 'questions/header'
  %ul
    - @questions.each do |question|
      %li
        %br/
        = link_to (question), class: "list-group-item" do
          %strong= question.caption
          %blockquote
            %p.lead= question.body
            %footer
              %strong= question.user.name
      %br/
      %i.fa.fa-comments.likes
        = question.answers.count
        Answers
      %i.fa.fa-user-plus.text-success
        = question.follows.count
        Follower(s)

app/views/questions/index.html.haml
%h4.center-align Questions
= render 'search'
= render 'header'

.tab-content
  #all.col.s12
    = render 'all'
  #following.col.s12
    = render 'followed'
  #interests.col.s12
    = render 'interest'
  - if client?
    #mine.col.s12
      = render 'mine'

app/views/questions/interest.html.haml
%section.views
  = render partial: 'questions/header'
  %ul
    - @questions.each do |question|
      %li
        %br/
        = link_to (question), class: "list-group-item" do
          %strong= question.caption
          %blockquote
            %p.lead= question.body
            %footer
              %strong= question.user.name
      %br/
      %i.fa.fa-comments.likes
        = question.answers.count
        Answers
      %i.fa.fa-user-plus.text-success
        = question.follows.count
        Follower(s)
      - unless question.users.include?(current_user)
        .pull-right
          = form_for Follow.new do |f|
            = hidden_field(:follow, :question_id, value: "#{question.id}")
            %div
              = button_tag type: "submit", class: "btn btn-success" do
                %i.fa.fa-comments
                  Follow

app/views/questions/new.html.haml
%h5.center-align New Question
= render 'form'

app/views/questions/show.html.haml
.form-wrapper
  .form-head
    %h5.center-align
      Question, asked by
      = @question.user.name
      = time_ago_in_words(@question.created_at)
      ago
  .form-body
    %p= @question.body
    %p
      Tags:
      = raw tag_links(@question.all_tags)

    - if @question.user == current_user
      = link_to "Edit", edit_question_path(@question), class: "btn mdi-editor-mode-edit"
    - if @question.answers.count > 0
      = link_to "Answers", answers_path(question: @question), class: 'btn mdi-action-announcement'
    -if verified_doctor?
      = link_to "Contribute", "#answer-modal", class: 'waves-effect waves-light btn modal-trigger'

    .modal#answer-modal
      .modal-content
        %i.right.mdi-navigation-close.modal-close
        = render 'answer_form'


= link_to 'Back to Questions', questions_path, class: 'btn mdi-navigation-chevron-left'