config/routes.rb
Rails.application.routes.draw do

  resources :articles
  resources :questions
  resources :hospital_lists
  resources :doctor_lists, except: [:edit, :update, :show]
  resources :hospital_verification_requests, except: [:edit, :update]
  resources :doctor_verification_requests, except: [:edit, :update]

  get 'tags/:tag', to: 'questions#index', as: "tag"
  get 'questions/autocomplete_tag_name'
  get 'questions/autocomplete_question_body'
  get 'articles/autocomplete_article_title'

  resources :reviews
  resources :hospitals
  resources :answers, except: [:show]
  resources :profiles, only: [:show, :index] #todo do we really need show????
  resource  :dashboard, only: :show
  resources :doctors
  resources :hospital_likes, only: [:new, :create, :destroy]
  resources :answer_likes, only: [:new, :create, :destroy]
  resources :doctor_likes, only: [:new, :create, :destroy]
  resources :follows, only: [:new, :create, :destroy]
  resources :ratings, only: :update

  post 'answer' => 'questions#answer'
  get 'hospitals/:id/doctors' => 'hospitals#our_doctors', as: :our_doctors

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => :registrations }

  root 'homes#show'

  mount Ckeditor::Engine => '/ckeditor'
end

app/models/doctor_list.rb
class DoctorList < ActiveRecord::Base
  belongs_to :user, -> { where(role: "doctor", verified: true) } #todo what about DoctorList.doctors for example?
  belongs_to :hospital

  validates_presence_of :user, :hospital
  validates :user, uniqueness: { message: "You have already been verified by a Hospital!" }
  validate :doctor_is_verified, :hospital_is_verified

  after_destroy :un_verify_doctor

  def doctor_is_verified
    errors.add(:user, "must be a verified doctor") unless self.user && self.user.role == "doctor" && self.user.verified == true
  end

  def hospital_is_verified
    errors.add(:hospital, "must be a verified") unless self.hospital && self.hospital.verified == true
  end

  protected

  def un_verify_doctor
    self.user.update_attributes(verified: false)
  end
end

app/controllers/doctor_lists_controller.rb
class DoctorListsController < ApplicationController
  before_action :set_doctor_list, only: [:show, :edit, :update, :destroy]
  # before_action :set_hospital, only: [:index]

  # GET /doctor_lists
  # GET /doctor_lists.json
  def index
    @doctor_lists = DoctorList.where(hospital_id: current_user.hospitals.map(&:id))
  end

  # GET /doctor_lists/1
  # GET /doctor_lists/1.json
  def show
  end

  # GET /doctor_lists/new
  def new
    @doctor_list = DoctorList.new
  end

  # GET /doctor_lists/1/edit
  def edit
  end

  # POST /doctor_lists
  # POST /doctor_lists.json
  def create
    @doctor_list = DoctorList.new(doctor_list_params)

    respond_to do |format|
      if @doctor_list.save
        format.html { redirect_to @doctor_list, notice: 'Doctor list was successfully created.' }
        format.json { render :show, status: :created, location: @doctor_list }
      else
        format.html { render :new }
        format.json { render json: @doctor_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctor_lists/1
  # PATCH/PUT /doctor_lists/1.json
  def update
    respond_to do |format|
      if @doctor_list.update(doctor_list_params)
        format.html { redirect_to @doctor_list, notice: 'Doctor list was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor_list }
      else
        format.html { render :edit }
        format.json { render json: @doctor_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctor_lists/1
  # DELETE /doctor_lists/1.json
  def destroy
    @doctor_list.destroy
    NotificationMailer.doctor_removed(@doctor_list.user, @doctor_list.hospital).deliver_now
    respond_to do |format|
      format.html { redirect_to doctor_lists_url, notice: 'Doctor list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor_list
      @doctor_list = DoctorList.find(params[:id])
    end

    # def set_hospital
    #   binding.pry
    #   @hospital = Hospital.find(params[:hospital])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_list_params
      params.require(:doctor_list).permit(:user_id, :hospital_id)
    end
end

app/views/doctor_lists/_form.html.haml
= form_for @doctor_list do |f|
  - if @doctor_list.errors.any?
    #error_explanation
      %h2= "#{pluralize(@doctor_list.errors.count, "error")} prohibited this doctor_list from being saved:"
      %ul
        - @doctor_list.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :hospital
    = f.text_field :hospital
  .actions
    = f.submit 'Save'

app/views/doctor_lists/edit.html.haml
%h1 Editing doctor_list

= render 'form'

= link_to 'Show', @doctor_list
\|
= link_to 'Back', doctor_lists_path

app/views/doctor_lists/index.html.haml
%h4.center-align Doctors List
- @doctor_lists.each do |doctor|
  -if hospital_manager? && doctor.hospital.manager == current_user
    .row
      .col.s9.m5.l4
        .card.medium
          .card-image.waves-effect.waves-block.waves-light
            = image_tag(doctor.user.image.url(:small), class: "responsive-img activator")
            %span.card-title
              = doctor.user.name
              |
              %i= "#{time_ago_in_words(doctor.user.current_sign_in_at)} ago"
          .card-content
            %span.card-title.activator.grey-text.text-darken-4
              .truncate
                %i.right.mdi-navigation-more-vert
                = doctor.user.bio
            .card-action
              = link_to 'View', profile_path(doctor.user), class: 'mdi-image-remove-red-eye'
              = link_to 'Un-Verify', doctor, class: 'mdi-action-delete', :method => :delete, :data => { :confirm => "Are you sure you no longer want this Doctor associated with #{doctor.hospital.name} hospital?" }
          .card-reveal
            %span.card-title.grey-text.text-darken-4
              = doctor.user.name
              %i.right.mdi-navigation-close
            %p= doctor.user.bio

app/views/doctor_lists/new.html.haml
%h1 New doctor_list

= render 'form'

= link_to 'Back', doctor_lists_path

app/views/doctor_lists/show.html.haml
%p
  %b User:
  = @doctor_list.user
%p
  %b Hospital:
  = @doctor_list.hospital

= link_to 'Edit', edit_doctor_list_path(@doctor_list)
\|
= link_to 'Back', doctor_lists_path