config/routes.rb
Rails.application.routes.draw do

  resources :articles
  resources :questions
  resources :hospital_lists
  resources :doctor_lists, except: [:edit, :update, :show]
  resources :hospital_verification_requests, except: [:edit, :update]
  resources :doctor_verification_requests, except: [:edit, :update]

  get 'tags/:tag', to: 'questions#index', as: "tag"
  get 'questions/autocomplete_tag_name'
  get 'questions/autocomplete_question_body'
  get 'articles/autocomplete_article_title'

  resources :reviews
  resources :hospitals
  resources :answers, except: [:show]
  resources :profiles, only: [:show, :index] #todo do we really need show????
  resource  :dashboard, only: :show
  resources :doctors
  resources :hospital_likes, only: [:new, :create, :destroy]
  resources :answer_likes, only: [:new, :create, :destroy]
  resources :doctor_likes, only: [:new, :create, :destroy]
  resources :follows, only: [:new, :create, :destroy]
  resources :ratings, only: :update

  post 'answer' => 'questions#answer'
  get 'hospitals/:id/doctors' => 'hospitals#our_doctors', as: :our_doctors

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => :registrations }

  root 'homes#show'

  mount Ckeditor::Engine => '/ckeditor'
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :writer, -> { where(role: "doctor") }, class_name: "User", foreign_key: 'user_id'
  has_many :ratings, dependent: :destroy

  scope :contains_text, -> (text) { where("title like ? OR content like ?", "%#{text}%", "%#{text}%")}

  validates :writer, :title, :content, presence: true
  validate :doc_is_a_verified_doctor

  def average_rating
    self.ratings.sum(:score) / self.ratings.size
  end

  def user_rating(user = current_user)
    Rating.find_by(article: self, user: user) || Rating.create(article: self, user: user, score: 0)
  end

  def doc_is_a_verified_doctor
    errors.add(:writer, "must be a verified doctor") unless self.writer and self.writer.role == "doctor" and self.writer.verified == true
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  autocomplete :article, :title
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    if params[:q]
      @articles = Article.contains_text("%#{params[:q]}%").order('created_at DESC')
    else
      @articles = Article.all.order('created_at DESC')
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @rating = @article.user_rating(current_user)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article successfully posted.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:user_id, :title, :content)
    end
end

app/views/articles/_form.html.haml
.form-wrapper
  .row
    = form_for @article do |f|
      - if @article.errors.any?
        #error_explanation
          %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
          %ul
            - @article.errors.full_messages.each do |msg|
              %li= msg

      .row
        .input-field.col.s12
          = f.text_area :title, class: "validate materialize-textarea"
          = f.label :title
      .row
        .input-field.col.s12
          = f.cktext_area :content, id: "review_content", ckeditor: {filebrowserImageBrowseUrl: '/ckeditor/pictures',
            height: '300',
            autoParagraph: true,
            toolbar: "Pure"}

      .actions.center-align
        = button_tag type: "submit", class: "waves-effect waves-light btn-large" do
          %i.mdi-content-send
            Save

app/views/articles/_rating.html.erb
<% content_for :scripts do %>
    <script>
        $('#star').raty({
            readOnly: true,
            score: <%= @article.average_rating %>,
            path: '/assets'
        });

        $('#user_star').raty({
            score: <%= @rating.score %>,
            path: '/assets',
            click: function(score, evt) {
                $.ajax({
                    url: '/ratings/' + <%= @rating.id %>,
                    type: 'PATCH',
                    data: { score: score }
                });
            }
        });
    </script>
<% end %>

app/views/articles/_search.html.haml
= form_tag [:articles], {:method => :get, :class => 'navbar-search pull-right', style:'margin-right:15px;'} do
  = text_field_tag 'q', @q, { placeholder: "Search Articles", autocomplete: articles_autocomplete_article_title_path }

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
= render 'search'
%h4.center-align Listing Articles


.row
  - @articles.each do |article|
    .col.s12.m6
      .card-panel.question-panel
        .row
          .col.s4
            %h6= raw article.title
            = image_tag(article.writer.image.url(:small), class: "responsive-img activator")
            - unless article.writer.image.url
              = image_tag('avatar.png', width: "50", class: "responsive-img")
          .col.s8
            .question-body
              = raw article.content
            .right.profile= time_ago_in_words(article.created_at)
        .row
          = link_to 'View', article, class: 'mdi-image-remove-red-eye btn'
- if verified_doctor?
  = link_to 'New Article', new_article_path, class: 'btn'

app/views/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
= render partial: 'rating'

%p
  %b User:
  = @article.user.name
%p
  %b Title:
  = @article.title
%p
  %b Content:
  = raw(@article.content)
%br/
%p Averate rating
#star

%p Your rating
#user_star

= link_to 'Edit', edit_article_path(@article)
|
= link_to 'Back', articles_path
= link_to 'delete', @article, method: :delete