config/routes.rb
Rails.application.routes.draw do

  resources :articles
  resources :questions
  resources :hospital_lists
  resources :doctor_lists, except: [:edit, :update, :show]
  resources :hospital_verification_requests, except: [:edit, :update]
  resources :doctor_verification_requests, except: [:edit, :update]

  get 'tags/:tag', to: 'questions#index', as: "tag"
  get 'questions/autocomplete_tag_name'
  get 'questions/autocomplete_question_body'
  get 'articles/autocomplete_article_title'

  resources :reviews
  resources :hospitals
  resources :answers, except: [:show]
  resources :profiles, only: [:show, :index] #todo do we really need show????
  resource  :dashboard, only: :show
  resources :doctors
  resources :hospital_likes, only: [:new, :create, :destroy]
  resources :answer_likes, only: [:new, :create, :destroy]
  resources :doctor_likes, only: [:new, :create, :destroy]
  resources :follows, only: [:new, :create, :destroy]
  resources :ratings, only: :update

  post 'answer' => 'questions#answer'
  get 'hospitals/:id/doctors' => 'hospitals#our_doctors', as: :our_doctors

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => :registrations }

  root 'homes#show'

  mount Ckeditor::Engine => '/ckeditor'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user, -> { where(role: "doctor") }
  belongs_to :question

  has_many :answer_likes, :dependent => :destroy

  validates_presence_of :content, :question, :user
  validate :doctor_is_verified

  def doctor_is_verified
    errors.add(:user, "must be a verified doctor") unless self.user && self.user.role == "doctor" && self.user.verified == true
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:update]
  before_action :set_question, only: [:index, :new]
  load_and_authorize_resource

  # GET /answers
  # GET /answers.json
  def index
    @answers = @question.answers
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = @question.answers.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = current_user.answers.new(answer_params)
    respond_to do |format|
      if @answer.save
        format.html { redirect_to :back, notice: 'Answer was successfully posted.' }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer.question, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to @answer.question, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    def set_question
      @question = Question.find(params[:question])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:question_id, :content)
    end
end

app/views/answers/_form.html.haml
.row.form-body
  = form_for @answer do |f|
    - if @answer.errors.any?
      #error_explanation
        %h2
          = pluralize(@answer.errors.count, "error")
          prohibited this question from being saved:
        %ul
          - @answer.errors.full_messages.each do |message|
            %li= message
    .field
      = hidden_field(:answer, :question_id, value: @answer.question_id )
    .row
      .input-field.col.s12
        = f.text_area :content, class: "validate materialize-textarea"
        %label{:for => "answer_content"} Answer
    .actions
      = button_tag type: "submit", class: "btn" do
        Post Help

app/views/answers/edit.html.haml
%h5.center-align Editing Question
= render 'form'

= link_to 'Back', questions_path

app/views/answers/index.html.haml
.answers-wrapper
  - unless @answers.empty?
    %h5.center-align Answers
    - @answers.each do |answer|
      .card-panel
        = answer.content
        = image_tag(answer.user.image.url(:thumb), class: 'responsive-img')
        .right
          .mdi-action-favorite= answer.answer_likes.count
          - if client? && !answer.answer_likes.map(&:user).include?(current_user)
            = link_to "Like", answer_likes_path(answer_id: answer.id, user_id: current_user.id), method: :post, class: 'btn'
        - if answer.user == current_user
          = link_to 'Edit', edit_answer_path(answer), class: 'btn mdi-editor-mode-edit'

app/views/answers/new.html.haml
%h5.center-align New Answer
= render 'form'
= link_to 'Back', questions_path